name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  
  CARGO_TERM_COLOR: always

jobs:

  building:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Upload Artifact
      uses: actions/upload-artifact@v2

  testing:
    needs: building
    runs-on: ubuntu-latest
    steps:
    - name: Download Build
      uses: actions/download-artifact@v2
    - name: Run Tests
      run: cargo test --verbose

  benchmarking:
    needs: testing
    runs-on: ubuntu-latest
    steps:
    - name: Download Build
      uses: actions/download-artifact@v2
    - name: Run Benchmarks
      run: cargo bench --verbose
