name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  
  CARGO_TERM_COLOR: always

jobs:

  building:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: build casim
      run: cargo build --verbose
    - name: upload artifact
      uses: actions/upload-artifact@v2

  testing:
    needs: building
    runs-on: ubuntu-latest
    steps:
    - name: Download build
      uses: actions/download-artifact@v2
      run: cargo test --verbose

  benchmarking:
    needs: testing
    runs-on: ubuntu-latest
    steps:
    - name: Download build
      uses: actions/download-artifact@v2
      run: cargo bench --verbose
