name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  
  CARGO_TERM_COLOR: always

jobs:

  building:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo build --verbose

  testing:
    needs: building
    runs-on: ubuntu-latest
    steps:
    - run: cargo test --verbose

  benchmarking:
    needs: testing
    runs-on: ubuntu-latest
    steps:
    - run: cargo bench --verbose
